url: https://imm13.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: International Macrostomum Meeting 2020
email: peter.ladurner@uibk.ac.at
description: "Macrostomum, flatworm, Innsbruck, Austria, adhesion, adhesive, bioadhesion, bio-glue, glue, regeneration, stem cell, cells, stemcells, sex allocation"


# Team names, titles and social links
people:
- name: Peter Ladurner
  pic: Pete
  position: PI
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: stack-overflow
      #url: #

- name: Robert Pjeta
  pic: Robert
  position: Post-Doc
  #social:
    #- title: email
      #url: pjeta.robert@uibk.ac.at
    #- title: facebook
      #url: #
    #- title: linkedin
      #url: #

- name: Philip Bertemes
  pic: Phil
  position: PhD student
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #

- name: Magdalena Knapp
  pic: Magdalena
  position: Master student
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #   
      
- name: Moritz Nowakowski
  pic: Moritz
  position: Master student
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #      
            
      
- name: Birte Mertens
  pic: Birte
  position: Lab Technician
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #      
      
- name: Nikolas Andresen
  pic: Niko
  position: Lab Technician intern
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #            

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
  #- title: twitter
    #url: http://twitter.com/jekyllrb
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket 
    #url: http://bitbucket.org/jekyll
  #- title: github
    #url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Technikerstrasse 25
  - line: Innsbruck, Tyrol, AUSTRIA

# Build settings
markdown: kramdown
permalink: pretty
