url: https://imm13.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: International Macrostomum Meeting 2020
email: peter.ladurner@uibk.ac.at
description: "Robert was here."


# Team names, titles and social links
people:
- name: Peter Ladurner
  pic: 1
  position: PI
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: stack-overflow
      #url: #

- name: Robert Pjeta
  pic: 4
  position: Post-Doc
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: linkedin
      #url: #

- name: Philip Bertemes
  pic: 4
  position: PhD
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #

- name: Magdalena Knapp
  pic: 4
  position: Master Student
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #   
      
- name: Moritz Nowakowski
  pic: 4
  position: Master Student
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #      
            
      
- name: Birte Mertens
  pic: 4
  position: Lab Technician
  #social:
    #- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Technikerstrasse 25
  - line: Innsbruck, Tyrol, AUSTRIA

# Build settings
markdown: kramdown
permalink: pretty
